    mission = [NSEntityDescription insertNewObjectForEntityForName:@"Mission" inManagedObjectContext:context];
    [mission setValuesForKeysWithDictionary:[NSDictionary dictionaryWithObjectsAndKeys:
         @"ACE", @"title",
         @"Advanced Composition Explorer (ACE)", @"headline",
         @"<p>The ACE's primary mission is to measure and compare the composition of several samples of matter, including the solar corona, the solar wind, and other interplanetary particle populations, the local interstellar medium (ISM), and galactic matter. ACE also provides near-real-time 24/7 continuous coverage of solar wind parameters and solar energetic particle intensities (space weather). When reporting space weather, ACE provides an advance warning (about one hour) of geomagnetic storms that can overload power grids, disrupt communications on Earth, and present a hazard to astronauts.</p>", @"text", 
         @"http://www.srl.caltech.edu/ACE/", @"url",
         @"bundle://thumbnailmission-ace.png", @"thumbnail",
         @"http://sunearth.gsfc.nasa.gov/spaceweather/missions/ace.png", @"imageUrl",
         @"bundle://mission-ace.png", @"image",
        nil
       ]];
    mission = [NSEntityDescription insertNewObjectForEntityForName:@"Mission" inManagedObjectContext:context];
    [mission setValuesForKeysWithDictionary:[NSDictionary dictionaryWithObjectsAndKeys:
         @"Hinode", @"title",
         @"Hinode (Sunrise)", @"headline",
         @"<p>An international mission (NASA, JAXA) to understand how energy generated by magnetic field changes on the sun triggers solar flares, flows of matter, and the heating of the upper atmosphere and corona. It employs three instruments: an extreme ultraviolet imaging spectrometer (EIS - NRL); an optical telescope (SOT-NAOJ), and a x-ray telescope (XRT-SAO).</p>", @"text", 
         @"http://solarb.msfc.nasa.gov/", @"url",
         @"bundle://thumbnailmission-hinode.png", @"thumbnail",
         @"http://sunearth.gsfc.nasa.gov/spaceweather/missions/hinode.png", @"imageUrl",
         @"bundle://mission-hinode.png", @"image",
        nil
       ]];
    mission = [NSEntityDescription insertNewObjectForEntityForName:@"Mission" inManagedObjectContext:context];
    [mission setValuesForKeysWithDictionary:[NSDictionary dictionaryWithObjectsAndKeys:
         @"SOHO", @"title",
         @"SOHO, the Solar and Heliospheric Observatory", @"headline",
         @"<p>SOHO is an international collaboration between ESA and NASA to study the Sun from its deep core to the outer corona and the solar wind.  SOHO was launched on December 2, 1995.", @"text", 
         @"http://www.nasa.gov/audience/foreducators/index.html", @"url",
         @"bundle://thumbnailmission-soho.png", @"thumbnail",
         @"http://sunearth.gsfc.nasa.gov/spaceweather/missions/soho.png", @"imageUrl",
         @"bundle://mission-soho.png", @"image",
        nil
       ]];
    mission = [NSEntityDescription insertNewObjectForEntityForName:@"Mission" inManagedObjectContext:context];
    [mission setValuesForKeysWithDictionary:[NSDictionary dictionaryWithObjectsAndKeys:
         @"STEREO", @"title",
         @"STEREO (Solar TErrestrial RElations Observatory)", @"headline",
         @"<p>STEREO is a 2-year NASA mission employing two nearly identical space-based observatories to provide the very first, 3-D 'stereo' images of the sun, used to study the nature of coronal mass ejections. These powerful solar eruptions are a major source of the magnetic disruptions on Earth and a key component of space weather, which can greatly affect satellite operations, communications, power systems, the lives of humans in space, and global climate.</p>", @"text", 
         @"http://stereo.jhuapl.edu/", @"url",
         @"bundle://thumbnailmission-stereo.png", @"thumbnail",
         @"http://sunearth.gsfc.nasa.gov/spaceweather/missions/stereo.png", @"imageUrl",
         @"bundle://mission-stereo.png", @"image",
        nil
       ]];
    mission = [NSEntityDescription insertNewObjectForEntityForName:@"Mission" inManagedObjectContext:context];
    [mission setValuesForKeysWithDictionary:[NSDictionary dictionaryWithObjectsAndKeys:
         @"THEMIS", @"title",
         @"THEMIS - Time History of Events and Macroscale Interactions during Substorms", @"headline",
         @"<p>Using five satellites, 20 ground-based observatories, and 10 magnetometers located in schools, THEMIS aims to unlock the magnetic mysteries of the Northern and Southern Lights or auroras. Earth’s magnetosphere stores energy from the solar wind. On average, several times a day, the magnetospheric system reaches a breaking point and must release its energy resulting in auroras. This sudden release of energy is called “substorm onset” and it can be thought of as the earthquake of the magnetosphere. THEMIS is designed to understand the timing of events before and after substorm onset, in order to understand this “magnetospheric earthquake.”</p>", @"text", 
         @"http://ds9.ssl.berkeley.edu/themis", @"url",
         @"bundle://thumbnailmission-themis.png", @"thumbnail",
         @"http://sunearth.gsfc.nasa.gov/spaceweather/missions/themis.png", @"imageUrl",
         @"bundle://mission-themis.png", @"image",
        nil
       ]];
    mission = [NSEntityDescription insertNewObjectForEntityForName:@"Mission" inManagedObjectContext:context];
    [mission setValuesForKeysWithDictionary:[NSDictionary dictionaryWithObjectsAndKeys:
         @"Ulysses", @"title",
         @"Ulysses", @"headline",
         @"<p>Ulysses completed three solar orbits in its 17 ½ year mission returning a wealth of data to help understand the global structure of our star, the Sun.  Ulysses is a joint mission of the National Aeronautics and Space Administration and the European Space Agency. The NASA portion of the mission is managed by the Jet Propulsion Laboratory.</p>", @"text", 
         @"http://ulysses.jpl.nasa.gov/", @"url",
         @"bundle://thumbnailmission-ulysses.png", @"thumbnail",
         @"http://sunearth.gsfc.nasa.gov/spaceweather/missions/ulysses.png", @"imageUrl",
         @"bundle://mission-ulysses.png", @"image",
        nil
       ]];
    mission = [NSEntityDescription insertNewObjectForEntityForName:@"Mission" inManagedObjectContext:context];
    [mission setValuesForKeysWithDictionary:[NSDictionary dictionaryWithObjectsAndKeys:
         @"Voyager", @"title",
         @"Voyager", @"headline",
         @"<p>The Twin Voyager spacecraft are exploring distant regions of space never before encountered by an object from Earth. Both spacecraft are in a vast region at the edge of our solar system where the solar wind runs up against the thin gas between the stars. Both Voyagers carry a message from Earth on a phonograph record protected by an inscribed golden disc.</p>", @"text", 
         @"http://voyager.jpl.nasa.gov/", @"url",
         @"bundle://thumbnailmission-voyager.png", @"thumbnail",
         @"http://sunearth.gsfc.nasa.gov/spaceweather/missions/voyager.png", @"imageUrl",
         @"bundle://mission-voyager.png", @"image",
        nil
       ]];
